#!/usr/bin/env node

var geojsontoosm = require('./'),
  opt = require('optimist')
    .usage('Usage: $0 FILE')
    .boolean('version').describe('version', 'display software version')
    .boolean('help').describe('help', 'print this help message'),
  argv = opt.argv,
  fs = require('fs'),
  readline = require('readline'),
  pack = require('./package.json');

if (argv.help) {
  return opt.showHelp();
}
if (argv.version) {
  process.stdout.write(pack.version + '\n');
  return;
}

var filename = argv._[0] || '';

var start = process.hrtime();
var datastream = (filename ? fs.createReadStream(filename) : process.stdin);
var lineCount = 0;
var rl = readline.createInterface({
  input: datastream,
  crlfDelay: Infinity
});
rl.on('line', (data) => {
  lineCount++;
  convert(JSON.parse(data));
}).on('close', (error) => {
  if (error) console.error(error);
  var end = process.hrtime(start);
  console.error(`${lineCount} lines processed at ${end[0]}s ${end[1] / 1000000}ms`);
  process.exit(1);
});

function convert(data) {
  var result = geojsontoosm(data);
  process.stdout.write(result);
}
